-- 1. Ensure system_settings table exists
CREATE TABLE IF NOT EXISTS public.system_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ensure attendance tables exist (if not already there)
CREATE TABLE IF NOT EXISTS public.member_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id UUID REFERENCES public.members(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    punch_in TIME WITHOUT TIME ZONE,
    punch_out TIME WITHOUT TIME ZONE,
    status TEXT DEFAULT 'Present',
    class_area TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.trainer_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id UUID REFERENCES public.trainers(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    punch_in TIME WITHOUT TIME ZONE,
    punch_out TIME WITHOUT TIME ZONE,
    status TEXT DEFAULT 'Present',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable RLS on all tables
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.member_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trainer_attendance ENABLE ROW LEVEL SECURITY;

-- 4. GRANT permissions to authenticated and anon roles
-- Explicitly granting usage and table permissions is often necessary for PostgREST
GRANT ALL ON TABLE public.system_settings TO authenticated, service_role;
GRANT ALL ON TABLE public.member_attendance TO authenticated, service_role;
GRANT ALL ON TABLE public.trainer_attendance TO authenticated, service_role;

GRANT SELECT ON TABLE public.system_settings TO anon;
GRANT SELECT ON TABLE public.member_attendance TO anon;
GRANT SELECT ON TABLE public.trainer_attendance TO anon;

-- 5. Create Policies (more robust checks)

-- Drop existing if any to avoid errors
DROP POLICY IF EXISTS "Allow admins full access to system_settings" ON public.system_settings;
DROP POLICY IF EXISTS "Allow admins full access to member_attendance" ON public.member_attendance;
DROP POLICY IF EXISTS "Allow admins full access to trainer_attendance" ON public.trainer_attendance;
DROP POLICY IF EXISTS "Public read access for system_settings" ON public.system_settings;

-- Policy: Allow anyone (even anon) to READ system settings (useful for login/app config)
CREATE POLICY "Public read access for system_settings" 
ON public.system_settings FOR SELECT 
TO public 
USING (true);

-- Policy: Allow admins full access (restricting Write/Update to admins)
CREATE POLICY "Admin full access to system_settings" 
ON public.system_settings FOR ALL 
TO authenticated 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 'admin'
  )
);

CREATE POLICY "Admin full access to member_attendance" 
ON public.member_attendance FOR ALL 
TO authenticated 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 'admin'
  )
);

CREATE POLICY "Admin full access to trainer_attendance" 
ON public.trainer_attendance FOR ALL 
TO authenticated 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- 6. Seed default values for system_settings
INSERT INTO public.system_settings (key, value)
VALUES 
    ('member_punch_limit', '1'),
    ('trainer_punch_limit', '1')
ON CONFLICT (key) DO NOTHING;
